# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('mother_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(max_length=128)),
                ('student_mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=128)),
                ('parent_mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
